on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # ビルド対象のマイコンボード（カンマ区切りで複数指定も可能）
      board: '["nice_nano_v2"]'
      # ビルド対象のシールド（左右それぞれを指定）
      shield: '["charybdis_left", "charybdis_right"]'
